### ISSUE TITLE
Research Kaikas wallet connection issues

### ISSUE THREAD

**Issue by shiki-tak** [Finschia/flutter-bird#12]

**Comment by da1suk8** [comment]
I encountered an issue when trying to connect Kaikas Wallet using Wallet Connect.

Upon investigation, I found that the problem was due to the version difference of Wallet Connect supported by Kaikas Wallet. Specifically, Kaikas Wallet only supports `v1`, while the widely used version is Wallet Connect `v2`.

Starting from `v2`, a project ID is required.
